### PR TITLE
add more bookmarklets + template

### PR DESCRIPTION
**Pull request by RuralAnemone**
https://github.com/3kh0/3kh0.github.io/issues/258

oh also some grammar + slight improvements in the main description

### CODE REVIEW

**Comment by venstillia** [comment]
🥱🥱🥱🥱 I wonder who got those bookmarklets 🥱🥱🥱🥱

**Comment by RuralAnemone** [comment]
:)

**Review by HENRYMARTIN5 — APPROVED** [review]
Looks good!

**Comment by 3kh0** [comment]
Yup, seems legit

**Pull request merged**
