### PR TITLE
Made Cubefield use js instead of Ruffle

### PR DESCRIPTION
**Pull request by SipSup3314**
The current version of Cubefield on this site uses Ruffle, which could be unstable and slow at times. While there is no way around this for many games, Cubefield is an exception. I added a js version instead of the flash version. Also the splash.png would have to be changed to 3kh0 and the title would have to have 3kh0 but it is fully working and is fairly fast on chromebooks.

### CODE REVIEW

**Review by 3kh0 — CHANGES_REQUESTED** [review]
Can you revert changes for `assets/splash.png`?

**Comment by 3kh0** [comment]
There are a few more minor issues but I can fix those

**Comment by SipSup3314** [comment]
I can only revert the entire request, not a single change. Please do that on your part.

**Comment by 3kh0** [comment]
Alr

**Pull request merged**
