### PR TITLE
add logo

### PR DESCRIPTION
**Pull request by nicolasog12**

### CODE REVIEW

**Review by 3kh0 — APPROVED** [review]
Code is good and it is looking good in the vercel preview

**Comment by 3kh0** [comment]
@nicolasog12 can you see if you can make a higher-res image and make a PR to replace the one we have currently.

**Comment by nicolasog12** [comment]
i will try to upscale the image and (maybe this sounds stupid) but wth is a PR

**Comment by 3kh0** [comment]
This this, a pull request, a pull, or a PR is what we devs call it 😄

**Pull request merged**
