### PR TITLE
sort of ui overhaul

### PR DESCRIPTION
**Pull request by kurbus**
first time doing css lol

### CODE REVIEW

**Comment by 3kh0** [comment]
Alr I will check this out

**Comment by 3kh0** [comment]
What does the alienhub resize do?

**Comment by kurbus** [comment]
> What does the alienhub resize do?

there's a large blank space between the logo and the alien ad, thought that might fix it

**Review by 3kh0 — CHANGES_REQUESTED** [review]
Leave the review as it was, the favicon should stay the same, and I like the background being the same dark grey

**Comment by kurbus** [comment]
git didnt wanna stage changes, thats why the hex color in index.css is one off
also deleted the vulnerability thing (t doesnt work, just throws errors every time its ran)
@3kh0 ur stuff's done

**Comment by kurbus** [comment]
aye dont merge this yet still workin

**Review by 3kh0 — CHANGES_REQUESTED** [review]
- Why did you move CONTRIBUTING.md? keep it in the .github folder
- On the new error pages please keep them indented with 2 spaces, you can do that https://unminify.com/
- Why are changing the colors of some pages
- Do not add more stuff to the main.js file
- Do not grey out the reviews

**Comment by kurbus** [comment]
> * Why did you move CONTRIBUTING.md? keep it in the .github folder
> * On the new error pages please keep them indented with 2 spaces, you can do that https://unminify.com/
> * Why are changing the colors of some pages
> * Do not add more stuff to the main.js file
> * Do not grey out the reviews

1. CONTRIBUTING.md is traditionally kept inside the root so that people can find it.
2. What's the reason to do that? 5** pages aren't normally seen by the user under normal circumstances, so keeping their design in line with the rest of the site is not that big of a deal.
3. To keep the design continuous between pages. The old one and the new one are virtually identical, anyway.
4. That's just clarification. "Injecting script" can seem a little scary to a bystander, so I wanted to clarify what it was doing,
5. I fixed that.

**Comment by 3kh0** [comment]
Alright I will git checkout in a bit

**Pull request merged**
