### PR TITLE
added wall smash from wallsmash.com

### PR DESCRIPTION
**Pull request by SipSup3314**
i added wallsmash from [https://wallsmash.com](https://wallsmash.com) by request of @Repsicoder

this time i added everything: tab title, main.js, and menu icon.
title: "Wall Smash | 3kh0"
script tag: "<script src="/js/main.js"></script>"
menu icon is in 1:1 ratio and button is titled "Wall Smash"

### CODE REVIEW

**Comment by 3kh0** [comment]
Woah, that works! Could you please remove the top scores since some people are not mature enough and have to enter in stupid usernames.

**Comment by 3kh0** [comment]
Wait, actually, don't, cuz then that ruins the point of scoring high. Oh well

**Comment by SipSup3314** [comment]
ok i know we closed this but the leaderboard may not work for some people because it connects to an external server, and that server might be blocked for some people. just clarifying

**Comment by Bountylnfinity** [comment]
@SipSup3314 This might just be my school district, but all iframes and external servers on websites are not blocked.

Another idea using Wallsmash is using the in-game chat to make a 3kh0 chat room. One of my IRL friends @Bennebotix did it and if you contact him he might give it to you.

**Comment by SipSup3314** [comment]
Cool. I will talk to him

**Pull request merged**
