### PR TITLE
fix about:blank embed not working with links without https:// (fixed so it doesnt add https:// onto links with http://)

### PR DESCRIPTION
**Pull request by fo-od**
:D took me a day (more like 4 hours) to do this easy edit but hey its good 👍

### CODE REVIEW

**Comment by Piplup7575** [comment]
I think something broke
https://user-images.githubusercontent.com/88395302/163628662-be23b2c3-ee17-4eec-b659-eeb60185e6fd.mp4

**Comment by fo-od** [comment]
oh crap ill fix that later today if i can figure it out im in school right now

**Comment by fo-od** [comment]
actually nothing is wrong with the edit its the about:blank thing itself i dont think it supports http:// links since i tested it on the original script and it shows blank

**Comment by 3kh0** [comment]
works for me, im gonna merge this

**Pull request merged**
