### PR TITLE
add gams

### PR DESCRIPTION
**Pull request by Rahib777-7**
gets rid of one of the blockers

### CODE REVIEW

**Comment by aeiea** [comment]
rahib can u review this pr #248

**Comment by Rahib777-7** [comment]
> rahib can u review this pr #248

that removes all adblocking code

**Comment by aeiea** [comment]
i changed all the adblock code

**Comment by Rahib777-7** [comment]
> i changed all the adblock code

yeah but they can still play games if they are using adblocker as for mines it works for people without adblocker or someone with a bypass method

**Comment by aeiea** [comment]
i think they already fix'd it

**Comment by aeiea** [comment]
Maybe try [Budibase](https://budibase.com/pricing/)?

**Pull request merged**
