### PR TITLE
[DRAFT] dynamically load projects

### PR DESCRIPTION
**Pull request by RuralAnemone**
#332

### CODE REVIEW

**Comment by RuralAnemone** [comment]
just doing this so I remember to do it lol :)

**Comment by RuralAnemone** [comment]
got dang why do I never open these as drafts 
💀

**Comment by 3kh0** [comment]
you can convert to a draft...

**Comment by RuralAnemone** [comment]
wait what

**Comment by RuralAnemone** [comment]
💀

**Comment by RuralAnemone** [comment]
how

**Comment by RuralAnemone** [comment]
oh wait I can't see the button because I already have a pr open for this branch
l'mao...?

**Pull request closed without merging**
