### PR TITLE
Adding Cut the Rope

### PR DESCRIPTION
**Pull request by Piplup7575**
IMagine porting cut the rope
added all files and updated projects page, hopefully no bugs, if there are I'll try to fix them.
enjoy!

### CODE REVIEW

**Comment by 3kh0** [comment]
Thank you @Piplup7575! I will make sure it is working well and I will merge!

**Comment by Piplup7575** [comment]
seems to work through vercel
should be open to merge!

**Comment by Piplup7575** [comment]
let me fix the favicon before you push it

**Comment by Piplup7575** [comment]
@3kh0 everything should work now, merge when ready!

**Comment by 3kh0** [comment]
Thank you so much @Piplup7575!

**Pull request merged**
