### PR TITLE
Make Changelog HTML

### PR DESCRIPTION
**Pull request by RetroWonder**

### CODE REVIEW

**Comment by RuralAnemone** [comment]
oh shoot I've been forgetting to use the changelog :0
oops

**Comment by RuralAnemone** [comment]
lol?

**Comment by RetroWonder** [comment]
oh no! XD

**Comment by RuralAnemone** [comment]
I may just do it rn 😏

**Comment by Piplup7575** [comment]
Sorry, not doing this, as the current changelog is fine and it would be more work to change to html lmao

**Pull request closed without merging**
