### PR TITLE
Finally made all flash games use one ruffle file

### PR DESCRIPTION
**Pull request by SipSup3314**
This reduces file size and allows you to easily update ruffle for all games at once. Also made the redirect in projects up to W3 standard.

### CODE REVIEW

**Review by 3kh0 — APPROVED** [review]
Thanks for the pull! Please move the ruffle-core folder to just the ruffle folder to make it cleaner

**Comment by 3kh0** [comment]
Also make sure you update the changelog!

**Comment by SipSup3314** [comment]
alr

**Comment by SipSup3314** [comment]
accidentally merged from main so all my progress is gone. i will redo this at home

**Comment by 3kh0** [comment]
Stale

**Pull request closed without merging**
