### PR TITLE
CSS Styles into seperate files

### PR DESCRIPTION
**Pull request by Juarez2010**
don't know if this would help or not, but I put some CSS from the HTML tags into separate files so it could be a bit more organized.

### CODE REVIEW

**Comment by 3kh0** [comment]
@Juarez2010 are you still working on this?

**Comment by Juarez2010** [comment]
Yeah, a bit. I closed it because you kept adding the styles in through the HTML tags so I thought it was basically pointless to put the styles into separate files.

**Comment by Juarez2010** [comment]
There are some conflicts though because I wasn't on for a day and I didn't fetch the changes in time so I have to open another PR because it won't let me just fetch the stream manually.

**Comment by 3kh0** [comment]
have no clue on how this work lol, the web editor for this is very confusing

**Comment by Juarez2010** [comment]
same lol

**Comment by Piplup7575** [comment]
I just shove things together in notepad and upload it, and it works :)
agreed, github is wack

**Pull request closed without merging**
