### PR TITLE
Add CroxyProxy links to proxy list

### PR DESCRIPTION
**Pull request by wearebuilders1233**
Added some new and cool proxies from croxyproxy (aka new proxy list);

### CODE REVIEW

**Comment by wearebuilders1233** [comment]
I forgot to link the image - 
croxyproxy

**Review by 3kh0 — CHANGES_REQUESTED** [review]
Can you add the croxyproxy image to the `img` directory?

**Review by Piplup7575 — CHANGES_REQUESTED** [review]
Looks good for now
Other than the image, the discord link is outdated, so that needs to be fixed
That's all!

**Comment by 3kh0** [comment]
Todo

- [ ] Fix image
- [ ] Fix Discord link (change it to https://discord.gg/wv6huJAwEv)

**Comment by wearebuilders1233** [comment]
Done! I also found a new HyperTabs link (https://bread.education) too, so I added it.

**Comment by 3kh0** [comment]
> Can you add the croxyproxy image to the `img` directory?

Make sure you do this aswell

**Review by Piplup7575 — APPROVED** [review]
👍

**Comment by 3kh0** [comment]
@nicolasog12

**Comment by nicolasog12** [comment]
Hello there I have been summoned

**Comment by nicolasog12** [comment]
Hello there I have been summoned :)

**Review by RuralAnemone — DISMISSED** [review]
looks good as far as I can tell

**Comment by 3kh0** [comment]
@nicolasog12 can you please fix the changes I have requested?

**Comment by nicolasog12** [comment]
> 

alright

**Comment by wearebuilders1233** [comment]
croxyproxy image is in there as
img/cp.jpg

**Review by 3kh0 — APPROVED** [review]
Looks good!

**Pull request merged**
