### PR TITLE
Add competitions (READ DESC BEFORE MERGING)

### PR DESCRIPTION
**Pull request by fowntain**
**YOU NEED TO FIX THE BUTTON CSS, THIS IS JUST THE BASIC CONCEPT.**
This would increase popularity and retention to your site.
[Live Demo](https://echoprs.netlify.app/competitions)

### CODE REVIEW

**Comment by Russell2259** [comment]
@fowntain Would this require an accounts system?

**Comment by Russell2259** [comment]
Remake: [https://russell2259.github.io/3kh0.github.io/leaderboard](https://russell2259.github.io/3kh0.github.io/leaderboard)

**Comment by fowntain** [comment]
> Remake: https://russell2259.github.io/3kh0.github.io/leaderboard

thanks, also will not requre acc system, if you clicked the submit button it takes you to a form

**Comment by Russell2259** [comment]
ok

**Review by 3kh0 — APPROVED** [review]

**Comment by 3kh0** [comment]
conflicts, pls resolve

**Review by 3kh0 — APPROVED** [review]

**Pull request merged**
