### PR TITLE
copyright update

### PR DESCRIPTION
**Pull request by silvereengames**
update the copyright date to 2023

### CODE REVIEW

**Comment by fartsindogs** [comment]
what does the copywrite mean exactally

**Comment by fartsindogs** [comment]
I meant what does the copywrite mean

**Comment by fartsindogs** [comment]
is it that people need permission to copy it

**Comment by silvereengames** [comment]
idk, it was their before and i just changed the date

**Comment by fartsindogs** [comment]
Oh ok

**Review by fartsindogs — APPROVED** [review]
Good

**Review by 3kh0 — APPROVED** [review]

**Pull request merged**
