### PR TITLE
Add support for sub-path forks, Update game-loading system

### PR DESCRIPTION
**Pull request by Russell2259**
Demo: [https://russell2259.github.io/3kh0.github.io/](url)

- Update game-loading system
- Using iframes
- Moved JSON files
- Updated some other stuff

Issue #95

### CODE REVIEW

**Review by 3kh0 — CHANGES_REQUESTED** [review]
for the json folder, rename it from `JSON` to `json`

**Comment by Russell2259** [comment]
@3kh0 Done

**Comment by Russell2259** [comment]
@3kh0 Wait... it's not loading from the path assets/json

**Comment by Russell2259** [comment]
@3kh0 I fixed it

**Review by 3kh0 — APPROVED** [review]

**Pull request merged**
