### PR TITLE
[EDIT]: Some silly code edits

### PR DESCRIPTION
**Pull request by nxxh447**

### CODE REVIEW

**Review by 3kh0 — CHANGES_REQUESTED** [review]
Code does not work, Uncaught TypeError: a is undefined

**Comment by nxxh447** [comment]
this error also makes no sense. the only thing I did was shorten the if/else (which clearly isn't the issue) and i declared the variables while also giving them a value, example:
```javascript
let foo = "bar";
```
while instead, you did
```javascript
let foo;
foo = "bar";
```
this shouldn't effect anything, the values of the variables weren't changed. the code must've not worked in the first place. maybe I'm wrong, I'm confused as well, if you see something i don't then please say something.

**Comment by 3kh0** [comment]
When I open console, this is the error, nothing happens, it does not filter

Screenshot_2022-12-14_09 43 10

**Comment by 3kh0** [comment]
Stale

**Pull request closed without merging**
