### PR TITLE
Add link to skool.world

### PR DESCRIPTION
**Pull request by thetatertotgod**
boost views without any visible changes

### CODE REVIEW

**Comment by Russell2259** [comment]
@thetatertotgod What does this do? Do you have a demo link?

**Comment by thetatertotgod** [comment]
i tested it on my site and it worked fine, didnt change position of surrounding objects

**Comment by Russell2259** [comment]
What does it do?

**Comment by thetatertotgod** [comment]
its a backlink so it would boost views on my site

**Comment by Russell2259** [comment]
._. talk to @3kh0 about that, but I don't think you can just advertise your site.

**Comment by thetatertotgod** [comment]
i have

**Comment by Russell2259** [comment]
ok

**Comment by 3kh0** [comment]
I really dont see why this is needed, and reading up on the google documentation, your link would not even be indexed as far as i can tell, so yeah.

**Pull request closed without merging**
