### PR TITLE
simplified projects list

### PR DESCRIPTION
**Pull request by Piplup7575**
added simplified projects list with search bar capability

### CODE REVIEW

**Comment by Piplup7575** [comment]
Should work now!

**Comment by coolman3289** [comment]
Is it added?

**Comment by Piplup7575** [comment]
> Is it added?

not yet, the pull request needs to be merged

all it does is add a link to the new page, should make it easier to find things

**Comment by Piplup7575** [comment]
woops the search function doesn't work, let me fix that

**Comment by Piplup7575** [comment]
@3kh0 Would something like this work?
image
the images on the side can be replaced, and the title can be changed to whatever you want it to be

**Comment by 3kh0** [comment]
Yes, but I have before tried using a search box and the photos really help the user with finding the games

**Comment by Piplup7575** [comment]
Oh
I was trying to make an alternate projects page, so it would be a bit easier to find things, but if you don't want it, that's fine!

**Pull request closed without merging**
