### PR TITLE
added spelunky

### PR DESCRIPTION
**Pull request by SipSup3314**

### CODE REVIEW

**Comment by Russell2259** [comment]
Do you want me to review?

**Review by Russell2259 — CHANGES_REQUESTED** [review]
looks good

**Comment by SipSup3314** [comment]
cool

**Review by Russell2259 — APPROVED** [review]

**Comment by SipSup3314** [comment]
thanks

**Comment by Russell2259** [comment]
I don't have write access for 3kh0-Assets

**Pull request merged**
