### PR TITLE
A fixed version of pr #119

### PR DESCRIPTION
**Pull request by Russell2259**
Oopsies

### CODE REVIEW

**Comment by Russell2259** [comment]
ur dischord is going crazy

**Review by 3kh0 — CHANGES_REQUESTED** [review]
What kind of fix does this do? You are just adding the file, not changing any links.

**Comment by Russell2259** [comment]
@3kh0 I was changing /assets/JSON to /assets/json but I didn't get to finish migrating the files before you merged.

You can see my version that is fixed and updated: https://russell2259.github.io/3kh0.github.io/

**Comment by Russell2259** [comment]
@3kh0 If I merge my fork with main it will overwrite my update.

**Comment by Russell2259** [comment]
@3kh0 It tried to update my fork so I just put a backup of the working version on the branch.

**Comment by Russell2259** [comment]
@3kh0 I should hopefully finally be done. Test url: https://russell2259.github.io/3kh0.github.io/

**Review by 3kh0 — APPROVED** [review]

**Pull request merged**
