### PR TITLE
Add rocket league

### PR DESCRIPTION
**Pull request by Rahib777-7**
it adds rocket league + optimises images

### CODE REVIEW

**Review by Russell2259 — APPROVED** [review]
Looks good.

**Review by Russell2259 — CHANGES_REQUESTED** [review]
Use new games system. [docs](https://github.com/3kh0/3kh0.github.io/wiki/Add-Game)

**Comment by Rahib777-7** [comment]
> Use new games system. [docs](https://github.com/3kh0/3kh0.github.io/wiki/Add-Game)

done

**Comment by Russell2259** [comment]
@Rahib777-7 That's the wrong file. Find `/assets/json/games.json`

**Comment by Rahib777-7** [comment]
> @Rahib777-7 That's the wrong file. Find `/assets/json/games.json`

done with right file now

**Comment by Russell2259** [comment]
@Rahib777-7 Please merge conflicts.

**Comment by Rahib777-7** [comment]
> @Rahib777-7 Please resolve conflicts.



> @Rahib777-7 Please resolve conflicts.

ok

**Review by Rahib777-7 — COMMENTED** [review]
comment

**Comment by Rahib777-7** [comment]
fuck it im too lazy to open the cmd line so ill just redo everything again

**Pull request closed without merging**
