### PR TITLE
Add some reviews

### PR DESCRIPTION
**Pull request by Piplup7575**
add these two reviews

### CODE REVIEW

**Comment by 3kh0** [comment]
Mention the issues that these close

**Review by 3kh0 — APPROVED** [review]
wait, nvm, just waiting for vercel

**Review by 3kh0 — CHANGES_REQUESTED** [review]
image

**Comment by Piplup7575** [comment]
jank!

**Comment by Piplup7575** [comment]
wait actualy

**Review by 3kh0 — CHANGES_REQUESTED** [review]
only 4 to a page, plus those should go after, the ohio one should be before these 2

**Comment by Piplup7575** [comment]
alright everything should now be fixed

**Review by 3kh0 — APPROVED** [review]

**Pull request merged**
