### PR TITLE
Added bitlife(without the limit)

### PR DESCRIPTION
**Pull request by smileman53**

### CODE REVIEW

**Comment by smileman53** [comment]
yay bitlife

**Comment by 3kh0** [comment]
image

**Comment by 3kh0** [comment]
@smileman53 any updates on this? Should I mark it as a draft?

**Comment by smileman53** [comment]
So the limit is still there? I didn’t see it for me. Hmm let me check

**Comment by smileman53** [comment]
https://html5.gamedistribution.com/rvvASMiM/2e44fb60fd3f4606b1b06c17a2b9d60d/index.html

**Comment by 3kh0** [comment]
@smileman53 see if you can add that game from the link you sent above

**Comment by smileman53** [comment]
It should work now

**Comment by 3kh0** [comment]
image

it still does it, try to visit the deployment, start a new life and just spam the new age button

**Comment by 3kh0** [comment]
Stale, reopen when you can get it to work

**Pull request closed without merging**
