### PR TITLE
clarity #2

### PR DESCRIPTION
**Pull request by kurbus**
I need to get the contributor badge again
if you could just give me write access that'd be spectacular

### CODE REVIEW

**Review by 3kh0 — CHANGES_REQUESTED** [review]
Not needed, and most of these changes are not required, if you want, update the games.json file in the assets folder for pulls on the 3kh0-Assets repo

**Comment by Nebelung-Dev** [comment]
> dont do copyright like this, esp if u dont actually have a copyright
3kh0 v3 had this

**Comment by Nebelung-Dev** [comment]
You basically changed some text to say a similar thing on the about page

**Comment by kurbus** [comment]
> You basically changed some text to say a similar thing on the about page

yeah because i need the contributor badge again and i dont have a laptop on me atm so i cant use vscode or anything else to do anything actually useful 
3kh0 pls no ban

**Pull request closed without merging**
