### PR TITLE
dynamically load projects (similar to `/projects/webretro/roms.html`)

### PR DESCRIPTION
**Pull request by RuralAnemone**
#332

### CODE REVIEW

**Comment by RuralAnemone** [comment]
opening this so I remember to do it lol :)

**Comment by mdoryammilwalrus** [comment]
I also wrote a script that does this

**Comment by 3kh0** [comment]
@mdoryammilwalrus Can you share it?

**Comment by RuralAnemone** [comment]
yes please do

**Comment by mdoryammilwalrus** [comment]
it is a fork and cannot pull orgin because of merge conflicts.

I will have to do some stuff with the command line

https://github.com/mdoryammilwalrus/3kh0.github.io

also you may have to git clone it and serve it on localhost with something like https://github.com/http-party/http-server

**Comment by mdoryammilwalrus** [comment]
Also did this: https://github.com/retronbv/buffy/pull/3

**Comment by mdoryammilwalrus** [comment]
@3kh0 updated the fork, updating the JSON files

Also check out https://github.com/retronbv/buffy/pull/3

**Comment by RuralAnemone** [comment]
might work on this tomorrow
sorry I haven't had much time lol

**Comment by mdoryammilwalrus** [comment]
I am also fixing the loader I made, every time a new game is added I have to redo the entire JSON file

**Comment by 3kh0** [comment]
Stale

**Comment by RuralAnemone** [comment]
ok

**Pull request closed without merging**
