### PR TITLE
Add Games

### PR DESCRIPTION
**Pull request by host008**
added games in 3kh0/3kh0-Assets#10

### CODE REVIEW

**Comment by host008** [comment]
not merging?

**Comment by host008** [comment]
I think you need to review it for it to merge.

**Comment by Russell2259** [comment]
@host008 I know that.

**Comment by Russell2259** [comment]
@host008 You need to update your 3kh0-assets fork

**Comment by host008** [comment]
wdym

**Review by Russell2259 — APPROVED** [review]
looks good

**Pull request merged**
