### PR TITLE
Starting to work on it

### PR DESCRIPTION
**Pull request by Vexify4**
What do you think of it, I need your input before I continue

### CODE REVIEW

**Comment by 3kh0** [comment]
Can you deploy the project on your branch so I can preview the changes and how it looks on the actual site?

**Review by 3kh0 — APPROVED** [review]
Looking good! Let me know if you need more image assests

**Comment by Vexify4** [comment]
https://vexify4.github.io/3kh0.github.io/games.html

**Comment by 3kh0** [comment]
This is great! I will use the existing code and make the rest be the same!

**Comment by 3kh0** [comment]
How would I add the images to the other games? Can you make some sort of universal template that I can use?

**Comment by Vexify4** [comment]
Let me finish the first row then I can get a idea of a universal template

**Comment by 3kh0** [comment]
> Let me finish the first row then I can get a idea of a universal template

Got it.

**Pull request merged**
