### PR TITLE
Add swordbattle

### PR DESCRIPTION
**Pull request by nicolasog12**
Add swordbattle, just like it says in the title. There might be bugs.

### CODE REVIEW

**Review by 3kh0 — CHANGES_REQUESTED** [review]
You need to add the listing on the projects page, and remove the image in the root directory at `assests/images/sword.png`

**Comment by nicolasog12** [comment]
>  remove the image in the root directory at `assests/images/sword.png`

why do i need to remove the image here?

**Comment by 3kh0** [comment]
> > remove the image in the root directory at `assests/images/sword.png`
> 
> why do i need to remove the image here?

Since it should not be made in a new directory in the root, all project files should be under `projects/swordbattle`

**Comment by nicolasog12** [comment]
> > > remove the image in the root directory at `assests/images/sword.png`
> > 
> > 
> > why do i need to remove the image here?
> 
> Since it should not be made in a new directory in the root, all project files should be under `projects/swordbattle`

i will investigate

**Comment by nicolasog12** [comment]
ok

**Comment by nicolasog12** [comment]
i think that swordbattle might not work with the thing i used to add it in :(

**Pull request closed without merging**
