### PR TITLE
Connect3

### PR DESCRIPTION
**Pull request by Piplup7575**
Candy Crush but bad.

### CODE REVIEW

**Comment by 3kh0** [comment]
Wait, @Piplup7575 the button goes to cookie clicker, can you fix that?

**Comment by Piplup7575** [comment]
Yeah one sec

**Comment by Piplup7575** [comment]
Ok there

**Comment by 3kh0** [comment]
image

404 Error?

**Comment by Piplup7575** [comment]
Strange, this might have fixed

**Comment by Piplup7575** [comment]
ima close this, will open a new one later when i figure out why its broken

**Pull request closed without merging**
