### PR TITLE
Add sandboxels

### PR DESCRIPTION
**Pull request by nicolasog12**

### CODE REVIEW

**Comment by RuralAnemone** [comment]
💀

**Comment by nicolasog12** [comment]
@RuralAnemone 
no

**Comment by 3kh0** [comment]
I will try to deploy this.

**Review by 3kh0 — APPROVED** [review]
Looks good so far, I just need to get vercel to work and deploy it.

**Review by 3kh0 — CHANGES_REQUESTED** [review]
Can you fix the names of the files in the `icons` directory? Remove the `�v=2` part on all of them since that might break things.

**Comment by nicolasog12** [comment]
Alright, done

**Review by 3kh0 — CHANGES_REQUESTED** [review]
Sorry that I did not see these before, but I need more changes, can you remove the back arrow on the main projects page.

image

And can you also remove the discord link at the buttons but keep the copyright and stuff. Once that is done, that should be it!

**Comment by nicolasog12** [comment]
alr finished

**Review by 3kh0 — APPROVED** [review]
Alright, that is good!

**Comment by 3kh0** [comment]
JUst waiting for deployment

**Comment by nicolasog12** [comment]
👍

**Pull request merged**
