### PR TITLE
added tiny fishing but source code

### PR DESCRIPTION
**Pull request by SipSup3314**
i added tiny fishing's source code as opposed to an iframe on https://github.com/3kh0/3kh0.github.io/pull/499

### CODE REVIEW

**Review by 3kh0 — CHANGES_REQUESTED** [review]
Please use the icon that you used in #499, it looks better, other than that good job! If you want you can close your other pull!

**Comment by SipSup3314** [comment]
I put the icon in. Also, I just wanted to clarify that I didn't make the other pull.

**Comment by 3kh0** [comment]
Oh yeah mb

**Comment by 3kh0** [comment]
I will merge this tmr, please update the changelog

**Comment by SipSup3314** [comment]
Way ahead of you on that

**Comment by 3kh0** [comment]
Please update the image on the projects list

**Comment by B0UNTYINFINITY** [comment]
Good Job, I couldn’t get the code to work!

**Comment by SipSup3314** [comment]
> Please update the image on the projects list

just did that now.

**Review by 3kh0 — APPROVED** [review]

**Pull request merged**
