### PR TITLE
added weave silk

### PR DESCRIPTION
**Pull request by SipSup3314**
I added weave silk from http://weavesilk.com. You will need to add the tab title, scripts, and the menu image coz I have no idea how you want them.
Edit: going to bed now so i will reply to any messages tomorrow

### CODE REVIEW

**Review by 3kh0 — CHANGES_REQUESTED** [review]
Tab title: `Weave Silk | 3kh0`
Add this: `<script src="/js/main.js"></script>`

**Comment by SipSup3314** [comment]
Done. I am assuming you will get the menu image yourself.

**Review by 3kh0 — CHANGES_REQUESTED** [review]
Please add a icon for the game, look it up on google and go to images

**Comment by SipSup3314** [comment]
Done.

**Review by 3kh0 — APPROVED** [review]

**Pull request merged**
