### PR TITLE
Add Offline paradise

### PR DESCRIPTION
**Pull request by Bennebotix**

### CODE REVIEW

**Review by 3kh0 — CHANGES_REQUESTED** [review]
Please fix the following issues:

- Update the game counter on the front page
- Add a card in the projects list for the game
- Find a good image to represent the game
- Add `<title>Offline Paradise | 3kh0</title>` in the <head> tags
- Add the site script, `<script src="/js/main.js"></script>`

**Comment by Bennebotix** [comment]
Ok.

**Comment by Bennebotix** [comment]
Where Was The Game Counter?

**Comment by Bennebotix** [comment]
Oh yeah also I can't add the image yet because the "./projects/OfflineParadise" folder doesn't exist yet but I have it.

**Comment by 3kh0** [comment]
@Bennebotix Just push it to the [`patch-1`](https://github.com/Bennebotix/3kh0.github.io/tree/patch-1) branch

**Comment by Bennebotix** [comment]
Ok So Two More Things @3kh0:
  My Branch Is One Commit Behind So If You Merge It Will Erase Your Last Commit.
  I Can't Find The Game Counter Where is It?

**Comment by Bennebotix** [comment]
Ok Merge Done Just Game Counter.

**Comment by Bennebotix** [comment]
Sorry.

**Comment by Bennebotix** [comment]
Ok Done. 189 I Think?

**Review by 3kh0 — CHANGES_REQUESTED** [review]
Can you run the code in https://unminify.com/ to make it look nicer?

**Comment by Bennebotix** [comment]
Sure!

**Comment by Bennebotix** [comment]
Done!

**Pull request merged**
