### PR TITLE
fixed unfair mario

### PR DESCRIPTION
**Pull request by aeiea**
it brok

### CODE REVIEW

**Comment by aeiea** [comment]
dont merge yet still broken

**Comment by aeiea** [comment]
3kh0/3kh0-assets#34

**Comment by aeiea** [comment]
can merge

**Comment by aeiea** [comment]
merging is ok

**Review by IcyonGit — APPROVED** [review]
Looks good to me.

**Review by host008 — APPROVED** [review]
the feared wrong json value

**Review by Russell2259 — APPROVED** [review]
Looks good.

**Pull request merged**
