### PR TITLE
make fork sync actually work

### PR DESCRIPTION
**Pull request by RuralAnemone**
not sure why I thought it worked before lol

### CODE REVIEW

**Comment by 3kh0** [comment]
I merged a pr, can you see if it works?

**Comment by 3kh0** [comment]
Please make sure that this does not run on this branch, or the main repo

**Comment by RuralAnemone** [comment]
wha
sorry I didn't really check which repo I was making a pr in
thought I was just merging to main!

my apologies

**Comment by RuralAnemone** [comment]
though I guess I could still leave this open

**Comment by RuralAnemone** [comment]
alright I actually provided a token this time lol

my repo is a bit behind so I'll just wait for the 30 minutes
it should work afaik

**Pull request closed without merging**
