### PR TITLE
Add 50+ Games

### PR DESCRIPTION
**Pull request by RetroWonder**
I have added over 50 games to my fork of 3kh0, however they are not visible to the public due to me making the files at 1AM on a Monday! (most games are emulated flash using ruffle, but some are WebGL)

### CODE REVIEW

**Comment by 3kh0** [comment]
WOAH

**Review by 3kh0 — CHANGES_REQUESTED** [review]
Can you update the projects list so that all of these games are here? Make sure you have a good description that is only 4 lines and a image with a 1:1 aspect ratio. Also check to make sure that the list is sorted alphabetically.

**Comment by 3kh0** [comment]
@RetroWonder Is this ready?

**Comment by Piplup7575** [comment]
Wasn't done yet lmao, there are 26 games not on the list but are in the files.
Will add.

**Pull request merged**
